listening-port=3478
min-port=49152
max-port=65535
fingerprint
no-multicast-peers
no-cli
no-tls
no-dtls
realm=kostky.propoj.app
user=kostky:VoiceChatTurnSecret2024
lt-cred-mech
external-ip=92.5.8.24/10.0.0.113
log-file=stdout
